services:
  ChefKnifeStudios.MartaJazz.server.webapi:
    build:
      context: .
      dockerfile: ./src/Server/ChefKnifeStudios.MartaJazz.Server.WebAPI/Dockerfile
    image: ${CONTAINER_REGISTRY:-localhost:5000}/ChefKnifeStudios.MartaJazz.server.webapi:${CONTAINER_TAG:-latest}
    ports:
      - "5268:8080"
