name: $(SourceBranchName)-chefknifestudios-transitjazz-client-$(Date:yyyyMMdd).$(Rev:r)

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildAndPublish
    jobs:
      - job: BuildAndPublish
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '10.x'
          - task: NuGetAuthenticate@1
          - script: dotnet workload install wasm-tools
            displayName: 'Install WASM tools'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: 'src/Client/ChefKnifeStudios.TransitJazz.Client.WebApp/ChefKnifeStudios.TransitJazz.Client.WebApp.csproj'
              arguments: '-c Release /p:BlazorEnableCompression=false'
              zipAfterPublish: false
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'src/Client/ChefKnifeStudios.TransitJazz.Client.WebApp/bin/Release/net10.0/publish/wwwroot'
              artifact: 'blazor-client'

  - stage: DeployProd
    dependsOn: BuildAndPublish
    condition: succeeded()
    jobs:
      - deployment: DeployProd
        environment: Production
        variables:
          - group: Prod-TransitJazz
        steps:
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/blazor-client/**'
              destinationFolder: '$(System.DefaultWorkingDirectory)/client'
          - script: |
              cd $(System.DefaultWorkingDirectory)/client/wwwroot
              echo '{"headers": {"Blazor-Environment": "Production"}}' > staticwebapp.config.json
            displayName: 'Update staticwebapp.config.json'
          - task: AzureStaticWebApp@0
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/client'
              azureSubscription: '$(TransitJazzWebDeploymentToken)'
              appLocation: '$(System.DefaultWorkingDirectory)/client'
              outputLocation: '$(System.DefaultWorkingDirectory)/client'
