name: $(SourceBranchName)-chefknifestudios-transitjazz-server-$(Date:yyyyMMdd).$(Rev:r)

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  azure-subscription-service-connection: TransitJazzSC
  container-registry: chefknife.azurecr.io
  api-container-name: ChefKnifeStudios.MartaJazz.server.webapi

stages:
  - stage: BuildAndPublish
    jobs:
      - job: BuildAndPush
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(azure-subscription-service-connection)'
              command: 'login'
          - script: |
              docker compose build
            displayName: 'Build Docker images'
          - script: |
              docker tag ChefKnifeStudios.MartaJazz.server.webapi:latest $(container-registry)/$(api-container-name):latest
              docker push $(container-registry)/$(api-container-name):latest
            displayName: 'Push API image'

  - stage: DeployProd
    dependsOn: BuildAndPublish
    condition: succeeded()
    jobs:
      - deployment: DeployProd
        environment: Production
        variables:
          - group: Prod-TransitJazz
        steps:
          - task: AzureContainerApps@1
            inputs:
              azureSubscription: '$(azure-subscription-service-connection)'
              resourceGroup: 'transit-jazz-rg'
              containerAppName: 'transit-jazz-api'
              imageToDeploy: '$(container-registry)/$(api-container-name):latest'
